---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: gcp
      backend: gcp
      controls:
        - gcp
    - name: local
      backend: local
      controls:
        - local

platforms:
  - name: dev
    driver:
      variables:
        env_name: dev
      variable_files:
        - test/variables/dev.json

suites:
  - name: folder
    driver:
      root_module_directory: modules/folder
  - name: project
    driver:
      root_module_directory: modules/project
